version: '3.8'

networks:
    chassi-network:

services:
    app:
        build:
            context: .container/php
            dockerfile: Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        image: laravel-app:latest
        container_name: chassi-laravel
        volumes:
            - ./:/var/www/html
            - ./storage/logs:/var/log/php
        depends_on:
            - mysql
            - redis
            - localstack
            - rabbitmq
        networks:
            - chassi-network

    nginx:
        image: nginx:latest
        container_name: chassi-nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - chassi-network

    mysql:
        image: mysql:8.0
        container_name: chassi-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u laravel -p laravel || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        networks:
            - chassi-network

    redis:
        image: redis:latest
        container_name: chassi-redis
        ports:
            - "6379:6379"
        networks:
            - chassi-network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: chassi-rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - chassi-network

    localstack:
        image: localstack/localstack
        container_name: chassi-localstack
        environment:
            - DOCKER_HOST=unix:///var/run/docker.sock
        ports:
            - "4566:4566"
            - "4510-4559:4510-4559"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - chassi-network

volumes:
    db_data:
    rabbitmq_data:
