services:
  app:
    build:
      context: .container/php
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/log/php
    depends_on:
      - db
      - redis
      - localstack

  web:
    image: nginx:latest
    container_name: laravel-web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u laravel -p laravel || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    container_name: laravel-redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"  # Porta para os serviços simulados da AWS
      - "4510-4559:4510-4559"  # Intervalo de portas para acesso aos serviços simulados
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Para comunicação com a máquina host

volumes:
  db_data:
